# Generated by Django 5.2.5 on 2025-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalschools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=255)),
                ('schooladdress', models.CharField(max_length=255)),
            ],
        ),
    ]
